version: '3'

services:
    bot:
      build: .
      container_name: bot
      image: bot_image
      env_file:
        - .env
      depends_on:
        - db

    db:
      container_name: db
      image: db_image
      env_file:
        - .env
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost replication all 0.0.0.0/0 md5"
        POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
      command: |
        postgres
        -c wal_level=replica
        -c hot_standby=on
        -c max_wal_senders=10
        -c max_replication_slots=10
        -c hot_standby_feedback=on
        -c log_replication_commands=on
      ports:
        - "5432:5432"
    db_repl:
      image: db_repl_image
      container_name: db_repl
      ports:
        - "5433:5432"
      environment:
        PGUSER: ${POSTGRES_USER}
        PGPASSWORD: ${POSTGRES_PASSWORD}
      depends_on:
        - db
